packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  fsevents: true
  msgpackr-extract: true
  sharp: false
  workerd: true

minimumReleaseAgeExclude:
  - "@alchemy.run/cloudflare-runtime@2.0.0-beta.74"
  - "@alchemy.run/floci@2.0.0-beta.74"
  - "@alchemy.run/node-utils@2.0.0-beta.74"
  - "@distilled.cloud/aws@1.0.0-rc.6"
  - "@distilled.cloud/axiom@1.0.0-rc.6"
  - "@distilled.cloud/cloudflare@1.0.0-rc.6"
  - "@distilled.cloud/core@1.0.0-rc.6"
  - "@distilled.cloud/fly-io@1.0.0-rc.6"
  - "@distilled.cloud/hetzner@1.0.0-rc.6"
  - "@distilled.cloud/neon@1.0.0-rc.6"
  - "@distilled.cloud/planetscale@1.0.0-rc.6"
  - alchemy@2.0.0-beta.74
  - "@cloudflare/workers-types@5.20260825.1"
  - "@voidzero-dev/vite-plus-core@0.3.0"
  - "@voidzero-dev/vite-plus-darwin-arm64@0.3.0"
  - "@voidzero-dev/vite-plus-darwin-x64@0.3.0"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu@0.3.0"
  - "@voidzero-dev/vite-plus-linux-arm64-musl@0.3.0"
  - "@voidzero-dev/vite-plus-linux-x64-gnu@0.3.0"
  - "@voidzero-dev/vite-plus-linux-x64-musl@0.3.0"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc@0.3.0"
  - "@voidzero-dev/vite-plus-win32-x64-msvc@0.3.0"
  - vite-plus@0.3.0
  - "@effect/platform-node-shared@4.0.0-rc.112"
  - "@effect/platform-node@4.0.0-rc.112"
  - "@effect/sql-sqlite-do@4.0.0-rc.112"
  - "@effect/vitest@4.0.0-rc.112"
  - "@oxlint/binding-android-arm-eabi@1.80.0"
  - "@oxlint/binding-android-arm64@1.80.0"
  - "@oxlint/binding-darwin-arm64@1.80.0"
  - "@oxlint/binding-darwin-x64@1.80.0"
  - "@oxlint/binding-freebsd-x64@1.80.0"
  - "@oxlint/binding-linux-arm-gnueabihf@1.80.0"
  - "@oxlint/binding-linux-arm-musleabihf@1.80.0"
  - "@oxlint/binding-linux-arm64-gnu@1.80.0"
  - "@oxlint/binding-linux-arm64-musl@1.80.0"
  - "@oxlint/binding-linux-ppc64-gnu@1.80.0"
  - "@oxlint/binding-linux-riscv64-gnu@1.80.0"
  - "@oxlint/binding-linux-riscv64-musl@1.80.0"
  - "@oxlint/binding-linux-s390x-gnu@1.80.0"
  - "@oxlint/binding-linux-x64-gnu@1.80.0"
  - "@oxlint/binding-linux-x64-musl@1.80.0"
  - "@oxlint/binding-openharmony-arm64@1.80.0"
  - "@oxlint/binding-win32-arm64-msvc@1.80.0"
  - "@oxlint/binding-win32-ia32-msvc@1.80.0"
  - "@oxlint/binding-win32-x64-msvc@1.80.0"
  - "@oxlint/plugins@1.80.0"
  - "@types/node@26.3.0"
  - effect@4.0.0-rc.112
  - oxlint@1.80.0

overrides:
  "@cloudflare/workers-types": "5.20260825.1"
  "@hono/node-server": "2.1.1"
  hono: "4.13.4"
  lodash: "4.18.1"
  valibot: "1.4.2"
  vite: "npm:@voidzero-dev/vite-plus-core@0.3.0"

patchedDependencies:
  alchemy: patches/alchemy-beta74-delete-when-upgrading-to-beta75.patch

peerDependencyRules:
  allowedVersions:
    typescript: "7.0.2"
    vite: "0.3.0"
